# Generated by Django 3.2.5 on 2021-12-19 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.CharField(choices=[(None, 'Выберите свою оценку'), ('1', 'Говно'), ('2', 'Блевать тянет'), ('3', 'Норм'), ('4', 'Класс'), ('5', 'Хорошо')], default='Выберите свою оценку', max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='news.rubric', verbose_name='Рубрика'),
        ),
    ]
