# Generated by Django 4.0 on 2022-01-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_sale_alter_category_name_alter_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='0'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sale',
            field=models.FloatField(default=0),
        ),
    ]
